### ISSUE TITLE
where does that video save?

### ISSUE THREAD

**Issue by guzukinfo** [Diphen-Hydramine/kavimo-download#18] opened 2024-04-11 11:40 UTC
how can I find the location video saved?

**Comment by Diphen-Hydramine** [comment] 2024-04-11 14:52
if download succeeds it's on the same folder that the app is on

**Comment by Diphen-Hydramine** [comment] 2024-04-11 20:25
Assuming the issue is resolved I will close this issue.
feel free to reopen if there are any problems

**Closed by Diphen-Hydramine** 2024-04-11 20:25 UTC
